Repository mskcc/cwl-commandlinetools, pull requests merged in 2019-07, with the labels that each got.

#26 Update Dockerfile
  trim_galore_0.6.2/container/Dockerfile
  trim_galore_0.6.2/trim_galore_0.6.2.cwl
Labels: bug

#25 Feature/abra2
  abra2_2.17/README.md
  abra2_2.17/abra2_2.17.cwl
  abra2_2.17/container/Dockerfile
  abra2_2.17/example_inputs.yaml
  abra2_2.19/README.md
  abra2_2.19/abra2_2.19.cwl
  abra2_2.19/container/Dockerfile
  abra2_2.19/example_inputs.yaml
Labels: enhancement

#8 Add Marianas 1.8.0 cwl
  marianas_process_loop_umi_1.8.0/container/Dockerfile
  marianas_process_loop_umi_1.8.0/marianas_process_loop_umi.cwl
Labels: enhancement

#20 Ss/mksas refactor
  waltz_count_reads_2.0.0/container/Dockerfile
  waltz_count_reads_2.0.0/example_inputs.yml
  waltz_count_reads_2.0.0/waltz_count_reads.cwl
Labels: help wanted

#49 Adding CWL for gzip and sort
  utilities_ubuntu_18.04/README.md
  utilities_ubuntu_18.04/example_inputs_gzip.yaml
  utilities_ubuntu_18.04/example_inputs_sort.yaml
  utilities_ubuntu_18.04/gzip.cwl
  utilities_ubuntu_18.04/sort.cwl
Labels: enhancement
